# Generated by Django 4.1.2 on 2022-10-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
